CompileFlags:
  Add: [
    -Wall, 
    # -I/usr/avr/include, 
    -I/usr/include/, 
    -I/usr/include/libxml2/, 
    # -D__AVR_ATmega328P__,
    -I$HOME/EE/ESP8266/ESP8266_RTOS_SDK/components/freertos/port/esp8266/include/freertos/,
    -I$HOME/EE/ESP8266/ESP8266_RTOS_SDK/components/freertos/include/,
    -I$HOME/EE/ESP8266/ESP8266_RTOS_SDK/components/esp8266/include/,
    -I$HOME/EE/ESP8266/ESP8266_RTOS_SDK/components/esp_http_server/include/,
    -I$HOME/EE/ESP8266/ESP8266_RTOS_SDK/components/http_parser/include/,
    -I$HOME/EE/ESP8266/ESP8266_RTOS_SDK/components/tcpip_adapter/include/,
    -I$HOME/EE/ESP8266/ESP8266_RTOS_SDK/components/esp_event/include/,
    -I$HOME/EE/ESP8266/ESP8266_RTOS_SDK/components/lwip/lwip/src/include/,
    -I$HOME/EE/ESP8266/ESP8266_RTOS_SDK/components/lwip/port/esp8266/include/,
    -I$HOME/EE/ESP8266/ESP8266_RTOS_SDK/components/freertos/include/freertos/private/,
    -I$HOME/EE/ESP8266/ESP8266_RTOS_SDK/components/freertos/port/esp8266/include/,
    -I$HOME/EE/ESP8266/ESP8266_RTOS_SDK/components/lwip/include/apps/sntp,
    -I$HOME/EE/ESP8266/ESP8266_RTOS_SDK/components/lwip/include/apps/,
    -I$HOME/EE/DeskLamp/Code/build/include/,
    -I$HOME/EE/ESP8266/ESP8266_RTOS_SDK/components/heap/include/,
    -I$HOME/EE/ESP8266/ESP8266_RTOS_SDK/components/heap/port/esp8266/include/,
    -I$HOME/EE/ESP8266/ESP8266_RTOS_SDK/components/esp_common/include/,
    -I$HOME/EE/ESP8266/ESP8266_RTOS_SDK/components/heap/port/esp8266/include/,
    -I$HOME/EE/ESP8266/ESP8266_RTOS_SDK/components/spi_flash/include/,
]
