CompileFlags:
  Add: [
    -Wall, 
    -Wextra,
    -Wshadow,
    -Wconversion, 
    -Wfloat-conversion,
    -Wmissing-prototypes,
    # -I/usr/avr/include, 
    -I/usr/include/, 
    -I/usr/include/libxml2/, 
    # -D__AVR_ATmega328P__,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/freertos/port/esp8266/include/freertos/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/freertos/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/esp8266/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/esp_http_server/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/http_parser/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/tcpip_adapter/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/esp_event/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/lwip/lwip/src/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/lwip/port/esp8266/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/freertos/include/freertos/private/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/freertos/port/esp8266/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/lwip/include/apps/sntp,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/lwip/include/apps/,
    # -I/home/mario/EE/DeskLamp/Code/build/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/heap/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/heap/port/esp8266/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/esp_common/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/heap/port/esp8266/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/spi_flash/include/,
    
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/esp_https_ota/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/protocomm/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/tcp_transport/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/heap/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/heap/port/esp8266/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/mqtt/esp-mqtt/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/mqtt/esp-mqtt/lib/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/wear_levelling/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/pthread/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/esp_common/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/http_parser/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/spi_ram/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/spi_flash/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/nvs_flash/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/freertos/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/freertos/port/esp8266/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/wifi_provisioning/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/bootloader_support/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/wpa_supplicant/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/wpa_supplicant/port/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/esp_ringbuf/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/jsmn/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/newlib/newlib/port/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/esp_gdbstub/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/mdns/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/openssl/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/lwip/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/lwip/port/esp8266/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/lwip/lwip/src/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/esp8266/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/libsodium/libsodium/src/libsodium/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/vfs/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/freemodbus/common/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/freemodbus/modbus/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/app_update/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/esp_event/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/esp-wolfssl/wolfssl/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/esp_http_server/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/esp_http_client/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/esp_http_client/lib/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/spiffs/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/log/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/mbedtls/port/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/mbedtls/mbedtls/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/coap/port/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/coap/libcoap/include/,
    # -I/home/mario/EE/ESP8266/ESP8266_RTOS_SDK/components/tcpip_adapter/include/,
]
